# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1122, 685)
        self.image_label_cam = QtWidgets.QLabel(Form)
        self.image_label_cam.setGeometry(QtCore.QRect(20, 70, 861, 591))
        self.image_label_cam.setText("")
        self.image_label_cam.setObjectName("image_label_cam")
        self.plainTextEdit_print = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_print.setGeometry(QtCore.QRect(900, 10, 211, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_print.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_print.setSizePolicy(sizePolicy)
        self.plainTextEdit_print.setObjectName("plainTextEdit_print")
        self.start_bt = QtWidgets.QPushButton(Form)
        self.start_bt.setGeometry(QtCore.QRect(900, 620, 211, 51))
        self.start_bt.setObjectName("start_bt")
        self.label_text = QtWidgets.QLabel(Form)
        self.label_text.setGeometry(QtCore.QRect(100, 20, 701, 31))
        self.label_text.setTextFormat(QtCore.Qt.AutoText)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.image_label_logo1 = QtWidgets.QLabel(Form)
        self.image_label_logo1.setGeometry(QtCore.QRect(30, 10, 48, 48))
        self.image_label_logo1.setText("")
        self.image_label_logo1.setObjectName("image_label_logo1")
        self.image_label_logo1.setPixmap(QtGui.QPixmap("ppns.png"))
        self.image_label_logo2 = QtWidgets.QLabel(Form)
        self.image_label_logo2.setGeometry(QtCore.QRect(820, 10, 48, 48))
        self.image_label_logo2.setText("")
        self.image_label_logo2.setObjectName("image_label_logo2")
        self.image_label_logo2.setPixmap(QtGui.QPixmap("to.png"))
        self.COM_Box = QtWidgets.QComboBox(Form)
        self.COM_Box.setGeometry(QtCore.QRect(1010, 500, 101, 31))
        self.COM_Box.setObjectName("COM_Box")
        self.COM_Box.addItem("")
        self.COM_Box.addItem("")
        self.COM_Box.addItem("")
        self.COM_Box.addItem("")
        self.COM_Box.addItem("")
        self.Baudrate_Box = QtWidgets.QComboBox(Form)
        self.Baudrate_Box.setGeometry(QtCore.QRect(1010, 540, 101, 31))
        self.Baudrate_Box.setObjectName("Baudrate_Box")
        self.Baudrate_Box.addItem("")
        self.Baudrate_Box.addItem("")
        self.label_text_2 = QtWidgets.QLabel(Form)
        self.label_text_2.setGeometry(QtCore.QRect(890, 500, 81, 21))
        self.label_text_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_2.setObjectName("label_text_2")
        self.label_text_3 = QtWidgets.QLabel(Form)
        self.label_text_3.setGeometry(QtCore.QRect(900, 540, 101, 31))
        self.label_text_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_text_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_3.setObjectName("label_text_3")
        self.connect_bt = QtWidgets.QPushButton(Form)
        self.connect_bt.setGeometry(QtCore.QRect(900, 580, 211, 31))
        self.connect_bt.setObjectName("connect_bt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.start_bt.setText(_translate("Form", "Start"))
        self.label_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sistem Peringatan Identifikasi APD Menggunakan YOLOv4</span></p></body></html>"))
        self.COM_Box.setItemText(0, _translate("Form", "COM1"))
        self.COM_Box.setItemText(1, _translate("Form", "COM2"))
        self.COM_Box.setItemText(2, _translate("Form", "COM3"))
        self.COM_Box.setItemText(3, _translate("Form", "COM4"))
        self.COM_Box.setItemText(4, _translate("Form", "COM5"))
        self.Baudrate_Box.setItemText(0, _translate("Form", "9600"))
        self.Baudrate_Box.setItemText(1, _translate("Form", "115200"))
        self.label_text_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">COM</span></p></body></html>"))
        self.label_text_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Baudrate</span></p></body></html>"))
        self.connect_bt.setText(_translate("Form", "Connect to Serial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
