# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1016, 595)
        self.image_label_cam = QtWidgets.QLabel(Form)
        self.image_label_cam.setGeometry(QtCore.QRect(20, 70, 731, 511))
        self.image_label_cam.setText("")
        self.image_label_cam.setObjectName("image_label_cam")
        self.plainTextEdit_print = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_print.setGeometry(QtCore.QRect(790, 10, 211, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_print.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_print.setSizePolicy(sizePolicy)
        self.plainTextEdit_print.setObjectName("plainTextEdit_print")
        self.start_bt = QtWidgets.QPushButton(Form)
        self.start_bt.setGeometry(QtCore.QRect(790, 530, 211, 51))
        self.start_bt.setObjectName("start_bt")
        self.label_text = QtWidgets.QLabel(Form)
        self.label_text.setGeometry(QtCore.QRect(90, 20, 591, 31))
        self.label_text.setTextFormat(QtCore.Qt.AutoText)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.image_label_logo1 = QtWidgets.QLabel(Form)
        self.image_label_logo1.setGeometry(QtCore.QRect(20, 10, 48, 48))
        self.image_label_logo1.setText("")
        self.image_label_logo1.setObjectName("image_label_logo1")
        self.image_label_logo2 = QtWidgets.QLabel(Form)
        self.image_label_logo2.setGeometry(QtCore.QRect(710, 10, 48, 48))
        self.image_label_logo2.setText("")
        self.image_label_logo2.setObjectName("image_label_logo2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.start_bt.setText(_translate("Form", "Start"))
        self.label_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sistem Peringatan Identifikasi APD Menggunakan YOLOv4</span></p></body></html>"))
